### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by ARR4NN** [mzmiric5/passport-patreon#1]
```
TypeError: Cannot read properties of undefined (reading 'id')
    at Request._callback (C:\Users\User\Documents\Websites\MemberManager\API\node_modules\passport-patreon\lib\passport-patreon\oauth2.js:33:25)
    at Request.self.callback (C:\Users\User\Documents\Websites\MemberManager\API\node_modules\request\request.js:185:22)
    at Request.emit (node:events:513:28)
    at Request.emit (node:domain:489:12)
    at Request.<anonymous> (C:\Users\User\Documents\Websites\MemberManager\API\node_modules\request\request.js:1154:10)
    at Request.emit (node:events:513:28)
    at Request.emit (node:domain:489:12)
    at IncomingMessage.<anonymous> (C:\Users\User\Documents\Websites\MemberManager\API\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (node:events:627:28)
    at IncomingMessage.emit (node:events:525:35)
```

**Comment by ARR4NN** [comment]
```
{
  errors: [
    {
      code: null,
      code_name: 'OAuthClientViewForbidden',
      detail: 'You do not have permission to view OAuth Client with id REDACTED.',
      id: 'bcf806cb-01e1-580b-b3f8-ca9e72a74d61',
      status: '403',
      title: 'You do not have permission to view this OAuth Client.'
    }
  ]
}
```

**Comment by Juraj-Masiar** [comment]
I have the same issue now when I use this library with my new testing Patreon account.
It worked fine with my "creator" account.

Any idea how to fix this? Maybe I'm just using a wrong scope?

EDIT:
Fixed by adding identity[email] to the scope: `['identity', 'identity[email]']`
EDIT2:
Actually, it can still fail with this error. I don't know if it's a race condition or Patreon API returns different values.
EDIT3:
As it turns out, it's the Patreon API that's buggy:
https://www.patreondevelopers.com/t/is-oauth-api-buggy-today/7235
